version: "3.9"
services:
  #################################
  # Seller: The seller microservice
  #################################
  seller:
    image: jialequek2020/seller:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/seller
    ports:
      - 5123:5000
  #################################  
  # MySQL
  #################################
  project-mysql:
      platform: linux/amd64
      image: project-database
      # maybe image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: user

      volumes: 
          - ./init:/docker-entrypoint-initdb.d

      ports:
        - 3306:3306
  
# adminer:
#     image: adminer
#     restart: always
#     ports:
#         - 8080:8080

# ***
# docker exec -it resources-docker-mysql2-1 bash -l
  # mysql -u user -p
  # show databases;