version: "3"
#platform: linux/x86_64
services:
  project-mysql:
    restart: always
    #    image: mysql:latest
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cart
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  #    mem_limit: 512m
  #    mem_reservation: 512m
  cart_webapp:
    restart: always
    #    image: pokemon:0.0.1-SNAPSHOT
    image: mon2020/cartapp:latest2
    depends_on:
      - project-mysql
    ports:
      - 9090:8080
    environment:
      - DATABASE_HOST=project-mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=cart
      - DATABASE_PORT=3306
    mem_limit: 750m
    mem_reservation: 700m
