version: '3.8'
#platform: linux/x86_64
services:
  inventory_webapp:
    restart: always
    #    image: pokemon:0.0.1-SNAPSHOT
    image: maars505/springinventory:CRUD2
    ports:
      - 9090:8080
    
    environment:
      DATABASE_HOST: project-mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: user
      DATABASE_NAME: inventory
      DATABASE_PORT: 3306
    # mem_limit: 750m
    # mem_reservation: 700m

    #./gradlew bootBuildImage --imageName=jialequek2020/springinventory:1.0  